CREATE TABLE public.aws_ec2_image_last_launched_times (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    image_arn text NOT NULL,
    last_launched_time timestamp without time zone
);
CREATE TABLE public.aws_ec2_image_launch_permissions (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    image_arn text,
    "group" text,
    organization_arn text,
    organizational_unit_arn text,
    user_id text
);
CREATE TABLE public.aws_ec2_images (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    region text NOT NULL,
    arn text NOT NULL,
    tags jsonb,
    architecture text,
    block_device_mappings jsonb,
    boot_mode text,
    creation_date text,
    deprecation_time text,
    description text,
    ena_support boolean,
    hypervisor text,
    image_id text,
    image_location text,
    image_owner_alias text,
    image_type text,
    imds_support text,
    kernel_id text,
    name text,
    owner_id text,
    platform text,
    platform_details text,
    product_codes jsonb,
    public boolean,
    ramdisk_id text,
    root_device_name text,
    root_device_type text,
    source_instance_id text,
    sriov_net_support text,
    state text,
    state_reason jsonb,
    tpm_support text,
    usage_operation text,
    virtualization_type text
);
CREATE TABLE public.aws_ec2_instances (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text,
    region text,
    arn text NOT NULL,
    state_transition_reason_time timestamp without time zone,
    tags jsonb,
    ami_launch_index bigint,
    architecture text,
    block_device_mappings jsonb,
    boot_mode text,
    capacity_reservation_id text,
    capacity_reservation_specification jsonb,
    client_token text,
    cpu_options jsonb,
    current_instance_boot_mode text,
    ebs_optimized boolean,
    elastic_gpu_associations jsonb,
    elastic_inference_accelerator_associations jsonb,
    ena_support boolean,
    enclave_options jsonb,
    hibernation_options jsonb,
    hypervisor text,
    iam_instance_profile jsonb,
    image_id text,
    instance_id text,
    instance_lifecycle text,
    instance_type text,
    ipv6_address text,
    kernel_id text,
    key_name text,
    launch_time timestamp without time zone,
    licenses jsonb,
    maintenance_options jsonb,
    metadata_options jsonb,
    monitoring jsonb,
    network_interfaces jsonb,
    outpost_arn text,
    placement jsonb,
    platform text,
    platform_details text,
    private_dns_name text,
    private_dns_name_options jsonb,
    private_ip_address text,
    product_codes jsonb,
    public_dns_name text,
    public_ip_address text,
    ramdisk_id text,
    root_device_name text,
    root_device_type text,
    security_groups jsonb,
    source_dest_check boolean,
    spot_instance_request_id text,
    sriov_net_support text,
    state jsonb,
    state_reason jsonb,
    state_transition_reason text,
    subnet_id text,
    tpm_support text,
    usage_operation text,
    usage_operation_update_time timestamp without time zone,
    virtualization_type text,
    vpc_id text
);
CREATE TABLE public.aws_iam_role_attached_policies (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    role_arn text NOT NULL,
    policy_arn text NOT NULL,
    policy_name text
);
CREATE TABLE public.aws_iam_role_last_accessed_details (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    role_arn text NOT NULL,
    job_id text,
    service_name text,
    service_namespace text NOT NULL,
    last_authenticated timestamp without time zone,
    last_authenticated_entity text,
    last_authenticated_region text,
    total_authenticated_entities bigint,
    tracked_actions_last_accessed jsonb
);
CREATE TABLE public.aws_iam_role_policies (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    role_arn text NOT NULL,
    policy_document jsonb,
    policy_name text NOT NULL,
    role_name text,
    result_metadata jsonb
);
CREATE TABLE public.aws_iam_roles (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    assume_role_policy_document jsonb,
    tags jsonb,
    arn text NOT NULL,
    create_date timestamp without time zone,
    path text,
    role_id text,
    role_name text,
    description text,
    max_session_duration bigint,
    permissions_boundary jsonb,
    role_last_used jsonb
);

CREATE TABLE public.aws_iam_signing_certificates (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    user_arn text NOT NULL,
    user_id text,
    certificate_body text,
    certificate_id text NOT NULL,
    status text,
    user_name text,
    upload_date timestamp without time zone
);
CREATE TABLE public.aws_iam_ssh_public_keys (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    user_arn text NOT NULL,
    user_id text,
    ssh_public_key_id text NOT NULL,
    status text,
    upload_date timestamp without time zone,
    user_name text
);


--
-- Name: aws_iam_user_access_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aws_iam_user_access_keys (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    user_arn text NOT NULL,
    access_key_id text NOT NULL,
    user_id text,
    last_used timestamp without time zone,
    last_used_service_name text,
    create_date timestamp without time zone,
    status text,
    user_name text,
    last_rotated timestamp without time zone
);
CREATE TABLE public.aws_iam_user_attached_policies (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    user_arn text NOT NULL,
    policy_name text NOT NULL,
    user_id text,
    policy_arn text
);
CREATE TABLE public.aws_iam_user_groups (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    user_arn text NOT NULL,
    user_id text,
    arn text NOT NULL,
    create_date timestamp without time zone,
    group_id text,
    group_name text,
    path text
);
CREATE TABLE public.aws_iam_user_last_accessed_details (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    user_arn text NOT NULL,
    job_id text,
    service_name text,
    service_namespace text NOT NULL,
    last_authenticated timestamp without time zone,
    last_authenticated_entity text,
    last_authenticated_region text,
    total_authenticated_entities bigint,
    tracked_actions_last_accessed jsonb
);
CREATE TABLE public.aws_iam_user_policies (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    user_arn text NOT NULL,
    user_id text,
    policy_document jsonb,
    policy_name text NOT NULL,
    user_name text,
    result_metadata jsonb
);
CREATE TABLE public.aws_iam_users (
    _cq_sync_time timestamp without time zone,
    _cq_source_name text,
    _cq_id uuid NOT NULL,
    _cq_parent_id uuid,
    account_id text NOT NULL,
    arn text NOT NULL,
    tags jsonb,
    create_date timestamp without time zone,
    path text,
    user_id text,
    user_name text,
    password_last_used timestamp without time zone,
    permissions_boundary jsonb
);